/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   syntax_analysis_table.h                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ishyian <ishyian@student.unit.ua>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/09/14 11:51:20 by ishyian           #+#    #+#             */
/*   Updated: 2019/09/16 15:28:24 by ishyian          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef SYNTAX_ANALYSIS_TABLE_H
# define SYNTAX_ANALYSIS_TABLE_H
# include "./asm.h"
# include "./syntax_analysis.h"

struct s_transition_table_	instruction_table[17][7] =
{
	[0][0] = {NULL},
	[0][1] = {NULL},
	[0][2] = {NULL},
	[0][3] = {NULL},
	[0][4] = {NULL},
	[0][5] = {NULL},
	[0][6] = {NULL},
	[1][0] = {is_dir},
	[1][1] = {is_endline},
	[1][2] = {NULL},
	[1][3] = {NULL},
	[1][4] = {NULL},
	[1][5] = {NULL},
	[1][6] = {NULL},
	[2][0] = {is_dir_ind},
	[2][1] = {is_sep},
	[2][2] = {is_reg},
	[2][3] = {is_endline},
	[2][4] = {NULL},
	[2][5] = {NULL},
	[2][6] = {NULL},
	[3][0] = {is_reg},
	[3][1] = {is_sep},
	[3][2] = {is_reg_ind},
	[3][3] = {is_endline},
	[3][4] = {NULL},
	[3][5] = {NULL},
	[3][6] = {NULL},
	[4][0] = {is_reg},
	[4][1] = {is_sep},
	[4][2] = {is_reg},
	[4][3] = {is_sep},
	[4][4] = {is_reg},
	[4][5] = {is_endline},
	[4][6] = {NULL},
	[5][0] = {is_reg},
	[5][1] = {is_sep},
	[5][2] = {is_reg},
	[5][3] = {is_sep},
	[5][4] = {is_reg},
	[5][5] = {is_endline},
	[5][6] = {NULL},
	[6][0] = {is_reg_dir_ind},
	[6][1] = {is_sep},
	[6][2] = {is_reg_dir_ind},
	[6][3] = {is_sep},
	[6][4] = {is_reg},
	[6][5] = {is_endline},
	[6][6] = {NULL},
	[7][0] = {is_reg_dir_ind},
	[7][1] = {is_sep},
	[7][2] = {is_reg_dir_ind},
	[7][3] = {is_sep},
	[7][4] = {is_reg},
	[7][5] = {is_endline},
	[7][6] = {NULL},
	[8][0] = {is_reg_dir_ind},
	[8][1] = {is_sep},
	[8][2] = {is_reg_dir_ind},
	[8][3] = {is_sep},
	[8][4] = {is_reg},
	[8][5] = {is_endline},
	[8][6] = {NULL},
	[9][0] = {is_dir},
	[9][1] = {is_endline},
	[9][2] = {NULL},
	[9][3] = {NULL},
	[9][4] = {NULL},
	[9][5] = {NULL},
	[9][6] = {NULL},
	[10][0] = {is_reg_dir_ind},
	[10][1] = {is_sep},
	[10][2] = {is_reg_dir},
	[10][3] = {is_sep},
	[10][4] = {is_reg},
	[10][5] = {is_endline},
	[10][6] = {NULL},
	[11][0] = {is_reg},
	[11][1] = {is_sep},
	[11][2] = {is_reg_dir_ind},
	[11][3] = {is_sep},
	[11][4] = {is_reg_dir},
	[11][5] = {is_endline},
	[11][6] = {NULL},
	[12][0] = {is_dir},
	[12][1] = {is_endline},
	[12][2] = {NULL},
	[12][3] = {NULL},
	[12][4] = {NULL},
	[12][5] = {NULL},
	[12][6] = {NULL},
	[13][0] = {is_dir_ind},
	[13][1] = {is_sep},
	[13][2] = {is_reg},
	[13][3] = {is_endline},
	[13][4] = {NULL},
	[13][5] = {NULL},
	[13][6] = {NULL},
	[14][0] = {is_reg_dir_ind},
	[14][1] = {is_sep},
	[14][2] = {is_reg_dir},
	[14][3] = {is_sep},
	[14][4] = {is_reg},
	[14][5] = {is_endline},
	[14][6] = {NULL},
	[15][0] = {is_dir},
	[15][1] = {is_endline},
	[15][2] = {NULL},
	[15][3] = {NULL},
	[15][4] = {NULL},
	[15][5] = {NULL},
	[15][6] = {NULL},
	[16][0] = {is_reg},
	[16][1] = {is_endline},
	[16][2] = {NULL},
	[16][3] = {NULL},
	[16][4] = {NULL},
	[16][5] = {NULL},
	[16][6] = {NULL},
};

#endif
